export const MAGUS = {
  slug: 'magus',
  nameKey: 'PF2E_LEVELER.MAGUS.NAME',
  compendiumUuid: 'Compendium.pf2e.classes.Item.Magus',
  keyAbility: ['str', 'dex'],
  hp: 8,

  featSchedule: {
    class: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    skill: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    general: [3, 7, 11, 15, 19],
    ancestry: [5, 9, 13, 17],
  },
  skillIncreaseSchedule: [3, 5, 7, 9, 11, 13, 15, 17, 19],
  abilityBoostSchedule: [5, 10, 15, 20],

  classFeatures: [
    { level: 5, name: 'Lightning Reflexes', key: 'lightning-reflexes' },
    { level: 5, name: 'Weapon Expertise', key: 'weapon-expertise' },
    { level: 7, name: 'Studious Spells', key: 'studious-spells' },
    { level: 7, name: 'Weapon Specialization', key: 'weapon-specialization' },
    { level: 9, name: 'Alertness', key: 'alertness' },
    { level: 9, name: 'Expert Spellcaster', key: 'expert-spellcaster' },
    { level: 9, name: 'Resolve', key: 'resolve' },
    { level: 11, name: 'Medium Armor Expertise', key: 'medium-armor-expertise' },
    { level: 13, name: 'Weapon Mastery', key: 'weapon-mastery' },
    { level: 15, name: 'Greater Weapon Specialization', key: 'greater-weapon-specialization' },
    { level: 15, name: 'Juggernaut', key: 'juggernaut' },
    { level: 17, name: 'Master Spellcaster', key: 'master-spellcaster' },
    { level: 17, name: 'Medium Armor Mastery', key: 'medium-armor-mastery' },
    { level: 19, name: 'Double Spellstrike', key: 'double-spellstrike' },
  ],

  spellcasting: {
    tradition: 'arcane',
    type: 'prepared',
    slots: {
      1: { cantrips: 5, 1: 1 },
      2: { cantrips: 5, 1: 2 },
      3: { cantrips: 5, 1: 2, 2: 1 },
      4: { cantrips: 5, 1: 2, 2: 2 },
      5: { cantrips: 5, 2: 2, 3: 2 },
      6: { cantrips: 5, 2: 2, 3: 2 },
      7: { cantrips: 5, 3: 2, 4: 2 },
      8: { cantrips: 5, 3: 2, 4: 2 },
      9: { cantrips: 5, 4: 2, 5: 2 },
      10: { cantrips: 5, 4: 2, 5: 2 },
      11: { cantrips: 5, 5: 2, 6: 2 },
      12: { cantrips: 5, 5: 2, 6: 2 },
      13: { cantrips: 5, 6: 2, 7: 2 },
      14: { cantrips: 5, 6: 2, 7: 2 },
      15: { cantrips: 5, 7: 2, 8: 2 },
      16: { cantrips: 5, 7: 2, 8: 2 },
      17: { cantrips: 5, 8: 2, 9: 2 },
      18: { cantrips: 5, 8: 2, 9: 2 },
      19: { cantrips: 5, 8: 2, 9: 2 },
      20: { cantrips: 5, 8: 2, 9: 2 },
    },
  },
};
