export const SWASHBUCKLER = {
  slug: 'swashbuckler',
  nameKey: 'PF2E_LEVELER.SWASHBUCKLER.NAME',
  compendiumUuid: 'Compendium.pf2e.classes.Item.Swashbuckler',
  keyAbility: ['dex'],
  hp: 10,

  featSchedule: {
    class: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    skill: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    general: [3, 7, 11, 15, 19],
    ancestry: [5, 9, 13, 17],
  },
  skillIncreaseSchedule: [3, 5, 7, 9, 11, 13, 15, 17, 19],
  abilityBoostSchedule: [5, 10, 15, 20],

  classFeatures: [
    { level: 3, name: 'Fortitude Expertise', key: 'fortitude-expertise' },
    { level: 3, name: 'Opportune Riposte', key: 'opportune-riposte' },
    { level: 3, name: 'Stylish Tricks', key: 'stylish-tricks' },
    { level: 3, name: 'Vivacious Speed', key: 'vivacious-speed' },
    { level: 5, name: 'Weapon Expertise', key: 'weapon-expertise' },
    { level: 7, name: 'Confident Evasion', key: 'confident-evasion' },
    { level: 7, name: 'Stylish Tricks', key: 'stylish-tricks' },
    { level: 7, name: 'Vivacious Speed', key: 'vivacious-speed' },
    { level: 7, name: 'Weapon Specialization', key: 'weapon-specialization' },
    { level: 9, name: 'Exemplary Finisher', key: 'exemplary-finisher' },
    { level: 9, name: 'Swashbuckler Expertise', key: 'swashbuckler-expertise' },
    { level: 11, name: 'Continuous Flair', key: 'continuous-flair' },
    { level: 11, name: 'Perception Mastery', key: 'perception-mastery' },
    { level: 11, name: 'Vivacious Speed', key: 'vivacious-speed' },
    { level: 13, name: 'Assured Evasion', key: 'assured-evasion' },
    { level: 13, name: 'Light Armor Expertise', key: 'light-armor-expertise' },
    { level: 13, name: 'Weapon Mastery', key: 'weapon-mastery' },
    { level: 15, name: 'Greater Weapon Specialization', key: 'greater-weapon-specialization' },
    { level: 15, name: 'Keen Flair', key: 'keen-flair' },
    { level: 15, name: 'Stylish Tricks', key: 'stylish-tricks' },
    { level: 15, name: 'Vivacious Speed', key: 'vivacious-speed' },
    { level: 17, name: 'Reinforced Ego', key: 'reinforced-ego' },
    { level: 19, name: 'Eternal Confidence', key: 'eternal-confidence' },
    { level: 19, name: 'Light Armor Mastery', key: 'light-armor-mastery' },
    { level: 19, name: 'Vivacious Speed', key: 'vivacious-speed' },
  ],

  spellcasting: null,
};
